version: "3"
services: 
  sample_db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: sample
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  sample_api:
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    environment:
      SAMPLE_DBHOST: sample_db
      SAMPLE_DBPORT: 3306
      SAMPLE_DBUSERNAME: root
      SAMPLE_DBPASSWORD: passw0rd
      SAMPLE_DBNAME: sample